[project]
name = "tg-botik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "asyncpg>=0.30.0",
    "psycopg[binary]>=3.2.10",
    "python-dotenv>=1.1.1",
]
