"""init

Revision ID: 0cfe5dd4d44b
Revises: 5f77196719a7
Create Date: 2025-11-14 21:22:06.021843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfe5dd4d44b'
down_revision: Union[str, Sequence[str], None] = '5f77196719a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'is_like',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'is_like',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
