"""add photo_id and gender interest

Revision ID: 673dde08d2cc
Revises: d5031ae4a770
Create Date: 2025-10-16 18:45:56.679313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673dde08d2cc'
down_revision: Union[str, Sequence[str], None] = 'd5031ae4a770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender_interest', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_id')
    op.drop_column('users', 'gender_interest')
    # ### end Alembic commands ###
