"""Add status_of_the_questionnaire to users

Revision ID: 6f3fa2e0f929
Revises: 673dde08d2cc
Create Date: 2025-10-20 13:43:09.266187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3fa2e0f929'
down_revision: Union[str, Sequence[str], None] = '673dde08d2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_of_the_questionnaire', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_of_the_questionnaire')
    # ### end Alembic commands ###
