"""make_fields_nullable

Revision ID: b9b301fbc557
Revises: cc2442976a16
Create Date: 2025-10-11 18:19:12.015095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9b301fbc557'
down_revision: Union[str, Sequence[str], None] = 'cc2442976a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='genderenum'),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'user_gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='genderenum'),
               nullable=False)
    # ### end Alembic commands ###
