"""make_fields_nullable1

Revision ID: d5031ae4a770
Revises: b9b301fbc557
Create Date: 2025-10-11 19:08:23.376983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5031ae4a770'
down_revision: Union[str, Sequence[str], None] = 'b9b301fbc557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='genderenum'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_gender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MALE', 'FEMALE', name='genderenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
